apiVersion: v1
kind: ConfigMap
metadata:
  name: flashsale-config
  namespace: flashsale
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_DATASOURCE_URL_ORDER: "jdbc:mysql://mysql:3306/orders_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_URL_INVENTORY: "jdbc:mysql://mysql:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_URL_PAYMENT: "jdbc:mysql://mysql:3306/payments_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/products_db"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "ecommerce-realm"
