global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "spring-actuator-bridge"
    honor_labels: true
    metrics_path: "/metrics"
    static_configs:
      - targets: ["metrics-exporter:9102", "host.docker.internal:9102"]
